---
name: Generic
about: File generic issues under this github issue template(use only if the issue does not match any of the other templates)
title: 'Operator: '
labels: ''
assignees: akondur

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Topology/Deployment setup on the K8s cluster
2. Steps to reproduce the issue

**Expected behavior**
A clear and concise description of what you expected to happen.

**Proposed changes(optional)**

**Screenshots(optional)**
If applicable, add screenshots to help explain your problem.

**System information**
- K8s environment(version of K8s, kind of K8s cluster eg. eks, aks etc)

**K8s collector [data](https://github.com/splunk/splunk-operator/blob/develop/docs/K8SCollectors.md) (optional)**

**Additional context(optional)**
Add any other context about the problem here.
