apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: nova-cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: nova-idc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: nova-cm
  replicas: 3
  startupProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
---
apiVersion: enterprise.splunk.com/v4
kind: SearchHeadCluster
metadata:
  name: nova-shc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: nova-cm
  startupProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
  livenessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
  readinessProbe:
    initialDelaySeconds: 120
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 12
