apiVersion: enterprise.splunk.com/v4
kind: ClusterManager
metadata:
  name: nova-cm
  finalizers:
  - enterprise.splunk.com/delete-pvc
---
apiVersion: enterprise.splunk.com/v4
kind: IndexerCluster
metadata:
  name: nova-idc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: nova-cm
  replicas: 3
---
apiVersion: enterprise.splunk.com/v4
kind: SearchHeadCluster
metadata:
  name: nova-shc
  finalizers:
  - enterprise.splunk.com/delete-pvc
spec:
  clusterManagerRef:
    name: nova-cm
